<a href="https://colab.research.google.com/github/sdsingh/learnstreet/blob/master/Pytorch_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [171]:
#@title Installing Pyorch

!pip install torch
!pip install torchvision

In [172]:
#@title Import Dependencies

import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable

In [173]:
#@title Define Hyperparameters

input_size = 784 # img_size = (28,28) ---> 28*28=784 in total
hidden_size = 500 # number of nodes at hidden layer
num_classes = 10 # number of output classes discrete range [0,9]
num_epochs = 20 # number of times which the entire dataset is passed throughout the model
batch_size = 100 # the size of input data took for one iteration
lr = 1e-3 # size of step

In [4]:
#@title Downloading MNIST data

train_data = dsets.MNIST(root = './data', train = True,
                        transform = transforms.ToTensor(), download = True)

test_data = dsets.MNIST(root = './data', train = False,
                       transform = transforms.ToTensor())

Failed to download (trying next):
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>



100%|██████████| 9.91M/9.91M [00:10<00:00, 941kB/s] 


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>



100%|██████████| 28.9k/28.9k [00:00<00:00, 135kB/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>



100%|██████████| 1.65M/1.65M [00:01<00:00, 1.11MB/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>



100%|██████████| 4.54k/4.54k [00:00<00:00, 4.33MB/s]

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



In [174]:
# data, targets. need to flatten train data.
print(train_data.data.size())
print(train_data.targets.size())

torch.Size([60000, 28, 28])
torch.Size([60000])


In [175]:
#@title Loading the data

train_gen = torch.utils.data.DataLoader(dataset = train_data,
                                             batch_size = batch_size,
                                             shuffle = True)

test_gen = torch.utils.data.DataLoader(dataset = test_data,
                                      batch_size = batch_size,
                                      shuffle = False)

In [176]:
#@title Define model class

class Net(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(Net,self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, num_classes)

  def forward(self,x):
    out = self.fc1(x)
    out = self.relu(out)
    out = self.fc2(out)
    return out

In [177]:
#@title Build the model

net = Net(input_size, hidden_size, num_classes)
if torch.cuda.is_available():
  net.cuda()

In [178]:
#@title Define loss-function & optimizer

loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [179]:
# zips over X, Y. batch dim is unsqueezed.
train_data[0][0].shape, train_data[0][1]

(torch.Size([1, 28, 28]), 5)

In [180]:
# Batch size 100.
# Why is the first dim still unsqueezed, wtf?
it = iter(train_gen)
batch = next(it)
print(batch[0].shape, batch[1].shape)

torch.Size([100, 1, 28, 28]) torch.Size([100])


In [181]:
# batch[0].view(-1,28*28).shape
batch[0].squeeze().view(-1, 28*28)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [182]:
#@title Training the model

for epoch in range(num_epochs):
  for i ,(images,labels) in enumerate(train_gen):
    # images = images.view(-1,28*28).cuda()
    # This is what I would've done, I don't quite get what view is doing here.
    images = images.squeeze().view(-1,input_size).cuda()
    labels = labels.cuda()

    optimizer.zero_grad()
    outputs = net(images)
    loss = loss_function(outputs, labels)
    loss.backward()
    optimizer.step()

    if (i+1) % 100 == 0:
      print('Epoch [%d/%d], Step [%d/%d], Loss: %.4f'
                 %(epoch+1, num_epochs, i+1, len(train_data)//batch_size, loss.item()))

Epoch [1/20], Step [100/600], Loss: 0.3725
Epoch [1/20], Step [200/600], Loss: 0.3215
Epoch [1/20], Step [300/600], Loss: 0.2335
Epoch [1/20], Step [400/600], Loss: 0.1476
Epoch [1/20], Step [500/600], Loss: 0.1539
Epoch [1/20], Step [600/600], Loss: 0.2030
Epoch [2/20], Step [100/600], Loss: 0.1003
Epoch [2/20], Step [200/600], Loss: 0.0911
Epoch [2/20], Step [300/600], Loss: 0.0862
Epoch [2/20], Step [400/600], Loss: 0.1409
Epoch [2/20], Step [500/600], Loss: 0.1142
Epoch [2/20], Step [600/600], Loss: 0.0705
Epoch [3/20], Step [100/600], Loss: 0.0806
Epoch [3/20], Step [200/600], Loss: 0.0401
Epoch [3/20], Step [300/600], Loss: 0.0271
Epoch [3/20], Step [400/600], Loss: 0.1076
Epoch [3/20], Step [500/600], Loss: 0.0502
Epoch [3/20], Step [600/600], Loss: 0.0231
Epoch [4/20], Step [100/600], Loss: 0.0361
Epoch [4/20], Step [200/600], Loss: 0.0929
Epoch [4/20], Step [300/600], Loss: 0.0164
Epoch [4/20], Step [400/600], Loss: 0.0807
Epoch [4/20], Step [500/600], Loss: 0.0242
Epoch [4/20

In [183]:
#@title Evaluating the accuracy of the model

correct = 0
total = 0
for images,labels in test_gen:
  images = Variable(images.view(-1,28*28)).cuda()
  labels = labels.cuda()

  output = net(images)
  _, predicted = torch.max(output,1)
  correct += (predicted == labels).sum()
  total += labels.size(0)

print('Accuracy of the model: %.3f %%' %((100*correct)/(total+1)))

Accuracy of the model: 98.340 %


In [184]:
for k in net.modules():
  # print(k, v)
  print(k)

Net(
  (fc1): Linear(in_features=784, out_features=500, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=500, out_features=10, bias=True)
)
Linear(in_features=784, out_features=500, bias=True)
ReLU()
Linear(in_features=500, out_features=10, bias=True)


In [185]:
m = list(net.modules())[1:]
m[0].weight.shape, m[0].bias.shape

(torch.Size([500, 784]), torch.Size([500]))

In [186]:
images.shape

torch.Size([100, 784])

In [199]:
optimizer.zero_grad()
# outputs = net(images)
# loss = loss_function(outputs, labels)
# outputs = net(images[:10, :])
# loss = loss_function(outputs, labels[:10])
outputs = net(images[0, :])
loss = loss_function(outputs, labels[0])
loss.backward()
# optimizer.step()

In [206]:
m[0].weight.grad.nonzero().shape

torch.Size([24881, 2])

In [201]:
m[0].weight.grad.shape

torch.Size([500, 784])

In [203]:
images[0, :].shape

torch.Size([784])

In [217]:
m[2].weight.grad.shape

torch.Size([10, 500])

In [219]:
m[2].bias.grad

tensor([ 1.5829e-11,  2.2958e-09,  3.2855e-07,  1.7072e-06,  2.6753e-13,
         8.4085e-08,  1.0949e-09,  1.8328e-13, -2.1458e-06,  8.5576e-13],
       device='cuda:0')

In [229]:
# correct shape already
e = torch.nn.functional.one_hot(labels[0], num_classes).unsqueeze(0)

In [232]:
(o - e).T *

torch.Size([1, 10])

In [ ]:
m[0].forward()

In [189]:
m[0].bias.grad.nonzero().shape

torch.Size([471, 1])

In [190]:
m[2].weight.grad.nonzero().shape

torch.Size([4708, 2])

In [191]:
optimizer.zero_grad()

In [227]:
with torch.no_grad():
  o = net(images[0, :].unsqueeze(0))
  print(o)

tensor([[-13.9104,  -8.9335,  -3.9699,  -2.3219, -17.9908,  -5.3327,  -9.6739,
         -18.3690,  10.9587, -16.8281]], device='cuda:0')


tensor([[-17.4796, -11.2568,  -7.1091,  -4.2298, -20.6758,  -8.2732, -16.1996,
         -35.7887,  15.9743, -24.6586]], device='cuda:0')

### Quick Manual Repro of Forward

In [154]:
# W * x + b
# W = (ninput x nhidden1)
# x = (ninput)
# b = nhidden1
h1 = torch.matmul(m[0].weight, images[0, :]) + m[0].bias
h1[h1 < 0] = 0.0
manual_o = torch.matmul(m[2].weight, h1) + m[2].bias

In [153]:
# doesn't work after relu
# torch.allclose(h1, m[0].forward(images[0, :]))

False

In [155]:
torch.allclose(o, manual_o)

True

In [159]:
torch.softmax(o, 1)

tensor([[2.9590e-15, 1.4917e-12, 9.4407e-11, 1.6806e-09, 1.2108e-16, 2.9473e-11,
         1.0643e-14, 3.3082e-23, 1.0000e+00, 2.2560e-18]], device='cuda:0')

In [160]:
o

tensor([[-17.4796, -11.2568,  -7.1091,  -4.2298, -20.6758,  -8.2732, -16.1996,
         -35.7887,  15.9743, -24.6586]], device='cuda:0')

In [215]:
m[1].

AttributeError: 'ReLU' object has no attribute 'grad'